"""Constants for the Hailuo AI TTS integration."""

DOMAIN = "hailuo_ai_tts"

CONF_GROUP_ID = "group_id"
CONF_API_KEY = "api_key"
CONF_SERVER = "server"
CONF_MODEL = "model"
CONF_SPEED = "speed"
CONF_VOL = "vol"
CONF_PITCH = "pitch"
CONF_VOICE = "voice"
CONF_EMOTION = "emotion"
CONF_ENGLISH_NORMALIZATION = "english_normalization"
CONF_LANGUAGE = "language"
CONF_MODEL_NAME = "model_name"
CONF_VOICE_NAME = "voice_name"
CONF_EMOTION_NAME = "emotion_name"
CONF_LANGUAGE_NAME = "language_name"
CONF_CUSTOM_VOICE_ID = "custom_voice_id"
CONF_CUSTOM_VOICE_NAME = "custom_voice_name"

# Default values
DEFAULT_LANGUAGE = "zh-HK"
DEFAULT_SERVER = "international"
DEFAULT_MODEL = "speech-2.6-turbo"
DEFAULT_SPEED = 1.0
DEFAULT_VOL = 1.0
DEFAULT_PITCH = 0
DEFAULT_ENGLISH_NORMALIZATION = False

# Available models
MODELS = {
    "speech-01-hd": "V1 HD",
    "speech-01-turbo": "V1 Turbo",
    "speech-02-hd": "V2 HD",
    "speech-02-turbo": "V2 Turbo",
    "speech-2.6-hd": "V2.6 HD",
    "speech-2.6-turbo": "V2.6 Turbo",
}

# Available emotions
EMOTIONS = {
    "happy": "Happy",
    "sad": "Sad",
    "angry": "Angry",
    "fearful": "Fearful",
    "disgusted": "Disgusted",
    "surprised": "Surprised",
    "calm": "Calm",
    "fluent": "Fluent (V2.6 ONLY)",
    "whisper": "Whisper (V2.6 ONLY)",
}

# Format: ISO code -> (API value, Display name)
LANGUAGE_MAPPINGS = {
    "zh-HK": ("Chinese,Yue", "Chinese (Cantonese)"),
    "zh-CN": ("Chinese", "Chinese (Mandarin)"),
    "en-UK": ("English", "English"),
    "en-US": ("English", "English"),
    "ar-EG": ("Arabic", "Arabic"),
    "ru-RU": ("Russian", "Russian"),
    "es-ES": ("Spanish", "Spanish"),
    "fr-FR": ("French", "French"),
    "pt-PT": ("Portuguese", "Portuguese"),
    "de-DE": ("German", "German"),
    "tr-TR": ("Turkish", "Turkish"),
    "nl-NL": ("Dutch", "Dutch"),
    "uk-UA": ("Ukrainian", "Ukrainian"),
    "vi-VN": ("Vietnamese", "Vietnamese"),
    "id-ID": ("Indonesian", "Indonesian"),
    "ja-JP": ("Japanese", "Japanese"),
    "it-IT": ("Italian", "Italian"),
    "ko-KR": ("Korean", "Korean"),
    "th-TH": ("Thai", "Thai"),
    "pl-PL": ("Polish", "Polish"),
    "ro-RO": ("Romanian", "Romanian"),
    "el-GR": ("Greek", "Greek"),
    "cs-CZ": ("Czech", "Czech"),
    "fi-FI": ("Finnish", "Finnish"),
    "hi-IN": ("Hindi", "Hindi"),
    "bg-BG": ("Bulgarian", "Bulgarian"),
    "da-DK": ("Danish", "Danish"),
    "he-IL": ("Hebrew", "Hebrew"),
    "ms-MY": ("Malay", "Malay"),
    "fa-IR": ("Persian", "Persian"),
    "sk-SK": ("Slovak", "Slovak"),
    "sv-SE": ("Swedish", "Swedish"),
    "hr-HR": ("Croatian", "Croatian"),
    "fil-PH": ("Filipino", "Filipino"),
    "hu-HU": ("Hungarian", "Hungarian"),
    "no-NO": ("Norwegian", "Norwegian"),
    "sl-SI": ("Slovenian", "Slovenian"),
    "ca-ES": ("Catalan", "Catalan"),
    "nn-NO": ("Nynorsk", "Nynorsk"),
    "ta-IN": ("Tamil", "Tamil"),
    "af-ZA": ("Afrikaans", "Afrikaans"),
    "auto": ("auto", "Auto"),
}

def get_language_api_value(iso_code: str) -> str:
    """Get the API language value from ISO code."""
    return LANGUAGE_MAPPINGS[iso_code][0]

def get_language_display_name(iso_code: str) -> str:
    """Get the display name from ISO code."""
    return LANGUAGE_MAPPINGS[iso_code][1]

TTS_VOICES = {
    "ar-EG": {
        "Arabic_CalmWoman": "Calm Woman",
        "Arabic_FriendlyGuy": "Friendly Guy",
    },
    "de-DE": {
        "German_FriendlyMan": "Friendly Man",
        "German_SweetLady": "Sweet Lady",
        "German_PlayfulMan": "Playful Man",
    },
    "en-UK": {
        "English_expressive_narrator": "Expressive Narrator",
        "English_compelling_lady1": "Compelling Lady",
        "English_Upbeat_Woman": "Upbeat Woman",
        "English_CalmWoman": "Calm Woman",
        "English_UpsetGirl": "Upset Girl",
        "English_Graceful_Lady": "Graceful Lady",
        "English_MaturePartner": "Mature Partner",
        "English_LovelyGirl": "Lovely Girl",
        "English_Deep-VoicedGentleman": "Deep-voiced Gentleman",
        "English_Wiselady": "Wise Lady",
        "English_DecentYoungMan": "Decent Young Man",
        "English_SentimentalLady": "Sentimental Lady",
        "English_ImposingManner": "Imposing Queen",
        "English_SadTeen": "Teen Boy",
        "English_WiseScholar": "Wise Scholar",
        "English_PatientMan": "Patient Man",
        "English_Comedian": "Comedian",
        "English_Strong-WilledBoy": "Strong-Willed Boy",
        "English_AnimeCharacter": "Female Narrator",
    },
    "en-US": {
        "English_radiant_girl": "Radiant Girl",
        "English_magnetic_voiced_man": "Magnetic-voiced Male",
        "English_Aussie_Bloke": "Aussie Bloke",
        "English_captivating_female1": "Captivating Female",
        "English_Trustworth_Man": "Trustworthy Man",
        "English_Gentle-voiced_man": "Gentle-voiced Man",
        "English_Whispering_girl": "Whispering girl",
        "English_Diligent_Man": "Diligent Man",
        "English_ReservedYoungMan": "Reserved Young Man",
        "English_PlayfulGirl": "Playful Girl",
        "English_ManWithDeepVoice": "Man With Deep Voice",
        "English_FriendlyPerson": "Friendly Guy",
        "English_MatureBoss": "Bossy Lady",
        "English_Debator": "Male Debater",
        "English_Steadymentor": "Reliable Man",
        "English_CaptivatingStoryteller": "Captivating Storyteller",
        "English_PassionateWarrior": "Passionate Warrior",
        "English_Soft-spokenGirl": "Soft-Spoken Girl",
        "English_SereneWoman": "Serene Woman",
        "English_ConfidentWoman": "Confident Woman",
        "English_BossyLeader": "Bossy Leader",
        "English_StressedLady": "Stressed Lady",
        "English_AssertiveQueen": "Assertive Queen",
        "English_Jovialman": "Jovial Man",
        "English_WhimsicalGirl": "Whimsical Girl",
        "English_Kind-heartedGirl": "Kind-Hearted Girl",
    },
    "es-ES": {
        "Spanish_SereneWoman": "Serene Woman",
        "Spanish_MaturePartner": "Mature Partner",
        "Spanish_CaptivatingStoryteller": "Captivating Storyteller",
        "Spanish_Narrator": "Narrator",
        "Spanish_WiseScholar": "Wise Scholar",
        "Spanish_Kind-heartedGirl": "Kind-hearted Girl",
        "Spanish_DeterminedManager": "Determined Manager",
        "Spanish_BossyLeader": "Bossy Leader",
        "Spanish_ReservedYoungMan": "Reserved Young Man",
        "Spanish_ConfidentWoman": "Confident Woman",
        "Spanish_ThoughtfulMan": "Thoughtful Man",
        "Spanish_Strong-WilledBoy": "Strong-willed Boy",
        "Spanish_SophisticatedLady": "Sophisticated Lady",
        "Spanish_RationalMan": "Rational Man",
        "Spanish_AnimeCharacter": "Anime Character",
        "Spanish_Deep-tonedMan": "Deep-toned Man",
        "Spanish_Fussyhostess": "Fussy hostess",
        "Spanish_SincereTeen": "Sincere Teen",
        "Spanish_FrankLady": "Frank Lady",
        "Spanish_Comedian": "Comedian",
        "Spanish_Debator": "Debator",
        "Spanish_ToughBoss": "Tough Boss",
        "Spanish_Wiselady": "Wise Lady",
        "Spanish_Steadymentor": "Steady Mentor",
        "Spanish_Jovialman": "Jovial Man",
        "Spanish_SantaClaus": "Santa Claus",
        "Spanish_Rudolph": "Rudolph",
        "Spanish_Intonategirl": "Intonate Girl",
        "Spanish_Arnold": "Arnold",
        "Spanish_Ghost": "Ghost",
        "Spanish_HumorousElder": "Humorous Elder",
        "Spanish_EnergeticBoy": "Energetic Boy",
        "Spanish_WhimsicalGirl": "Whimsical Girl",
        "Spanish_StrictBoss": "Strict Boss",
        "Spanish_ReliableMan": "Reliable Man",
        "Spanish_SereneElder": "Serene Elder",
        "Spanish_AngryMan": "Angry Man",
        "Spanish_AssertiveQueen": "Assertive Queen",
        "Spanish_CaringGirlfriend": "Caring Girlfriend",
        "Spanish_PowerfulSoldier": "Powerful Soldier",
        "Spanish_PassionateWarrior": "Passionate Warrior",
        "Spanish_ChattyGirl": "Chatty Girl",
        "Spanish_RomanticHusband": "Romantic Husband",
        "Spanish_CompellingGirl": "Compelling Girl",
        "Spanish_PowerfulVeteran": "Powerful Veteran",
        "Spanish_SensibleManager": "Sensible Manager",
        "Spanish_ThoughtfulLady": "Thoughtful Lady",
    },
    "fr-FR": {
        "French_Male_Speech_New": "Level-Headed Man",
        "French_Female_News Anchor": "Patient Female Presenter",
        "French_CasualMan": "Casual Man",
        "French_MovieLeadFemale": "Movie Lead Female",
        "French_FemaleAnchor": "Female Anchor",
        "French_MaleNarrator": "Male Narrator",
    },
    "id-ID": {
        "Indonesian_SweetGirl": "Sweet Girl",
        "Indonesian_ReservedYoungMan": "Reserved Young Man",
        "Indonesian_CharmingGirl": "Charming Girl",
        "Indonesian_CalmWoman": "Calm Woman",
        "Indonesian_ConfidentWoman": "Confident Woman",
        "Indonesian_CaringMan": "Caring Man",
        "Indonesian_BossyLeader": "Bossy Leader",
        "Indonesian_DeterminedBoy": "Determined Boy",
        "Indonesian_GentleGirl": "Gentle Girl",
    },
    "it-IT": {
        "Italian_BraveHeroine": "Brave Heroine",
        "Italian_Narrator": "Narrator",
        "Italian_WanderingSorcerer": "Wandering Sorcerer",
        "Italian_DiligentLeader": "Diligent Leader",
    },
    "ja-JP": {
        "Japanese_IntellectualSenior": "Intellectual Senior",
        "Japanese_DecisivePrincess": "Decisive Princess",
        "Japanese_LoyalKnight": "Loyal Knight",
        "Japanese_DominantMan": "Dominant Man",
        "Japanese_SeriousCommander": "Serious Commander",
        "Japanese_ColdQueen": "Cold Queen",
        "Japanese_DependableWoman": "Dependable Woman",
        "Japanese_GentleButler": "Gentle Butler",
        "Japanese_KindLady": "Kind Lady",
        "Japanese_CalmLady": "Calm Lady",
        "Japanese_OptimisticYouth": "Optimistic Youth",
        "Japanese_GenerousIzakayaOwner": "Generous Izakaya Owner",
        "Japanese_SportyStudent": "Sporty Student",
        "Japanese_InnocentBoy": "Innocent Boy",
        "Japanese_GracefulMaiden": "Graceful Maiden",
    },
    "ko-KR": {
        "Korean_AirheadedGirl": "Airheaded Girl",
        "Korean_AthleticGirl": "Athletic Girl",
        "Korean_AthleticStudent": "Athletic Student",
        "Korean_BraveAdventurer": "Brave Adventurer",
        "Korean_BraveFemaleWarrior": "Brave Female Warrior",
        "Korean_BraveYouth": "Brave Youth",
        "Korean_CalmGentleman": "Calm Gentleman",
        "Korean_CalmLady": "Calm Lady",
        "Korean_CaringWoman": "Caring Woman",
        "Korean_CharmingElderSister": "Charming Elder Sister",
        "Korean_CharmingSister": "Charming Sister",
        "Korean_CheerfulBoyfriend": "Cheerful Boyfriend",
        "Korean_CheerfulCoolJunior": "Cheerful Cool Junior",
        "Korean_CheerfulLittleSister": "Cheerful Little Sister",
        "Korean_ChildhoodFriendGirl": "Childhood Friend Girl",
        "Korean_CockyGuy": "Cocky Guy",
        "Korean_ColdGirl": "Cold Girl",
        "Korean_ColdYoungMan": "Cold Young Man",
        "Korean_ConfidentBoss": "Confident Boss",
        "Korean_ConsiderateSenior": "Considerate Senior",
        "Korean_DecisiveQueen": "Decisive Queen",
        "Korean_DominantMan": "Dominant Man",
        "Korean_ElegantPrincess": "Elegant Princess",
        "Korean_EnchantingSister": "Enchanting Sister",
        "Korean_EnthusiasticTeen": "Enthusiastic Teen",
        "Korean_FriendlyBigSister": "Friendly Big Sister",
        "Korean_GentleBoss": "Gentle Boss",
        "Korean_GentleWoman": "Gentle Woman",
        "Korean_HaughtyLady": "Haughty Lady",
        "Korean_InnocentBoy": "Innocent Boy",
        "Korean_IntellectualMan": "Intellectual Man",
        "Korean_IntellectualSenior": "Intellectual Senior",
        "Korean_LonelyWarrior": "Lonely Warrior",
        "Korean_MatureLady": "Mature Lady",
        "Korean_MysteriousGirl": "Mysterious Girl",
        "Korean_OptimisticYouth": "Optimistic Youth",
        "Korean_PlayboyCharmer": "Playboy Charmer",
        "Korean_PossessiveMan": "Possessive Man",
        "Korean_QuirkyGirl": "Quirky Girl",
        "Korean_ReliableSister": "Reliable Sister",
        "Korean_ReliableYouth": "Reliable Youth",
        "Korean_SassyGirl": "Sassy Girl",
        "Korean_ShyGirl": "Shy Girl",
        "Korean_SoothingLady": "Soothing Lady",
        "Korean_StrictBoss": "Strict Boss",
        "Korean_SweetGirl": "Sweet Girl",
        "Korean_ThoughtfulWoman": "Thoughtful Woman",
        "Korean_WiseElf": "Wise Elf",
        "Korean_WiseTeacher": "Wise Teacher",
    },
    "nl-NL": {
        "Dutch_kindhearted_girl": "Kind-hearted girl",
        "Dutch_bossy_leader": "Bossy leader",
    },
    "pt-PT": {
        "Portuguese_SentimentalLady": "Sentimental Lady",
        "Portuguese_BossyLeader": "Bossy Leader",
        "Portuguese_Wiselady": "Wise lady",
        "Portuguese_Strong-WilledBoy": "Strong-willed Boy",
        "Portuguese_Deep-VoicedGentleman": "Deep-voiced Gentleman",
        "Portuguese_UpsetGirl": "Upset Girl",
        "Portuguese_PassionateWarrior": "Passionate Warrior",
        "Portuguese_AnimeCharacter": "Anime Character",
        "Portuguese_ConfidentWoman": "Confident Woman",
        "Portuguese_AngryMan": "Angry Man",
        "Portuguese_CaptivatingStoryteller": "Captivating Storyteller",
        "Portuguese_Godfather": "Godfather",
        "Portuguese_ReservedYoungMan": "Reserved Young Man",
        "Portuguese_SmartYoungGirl": "Smart Young Girl",
        "Portuguese_Kind-heartedGirl": "Kind-hearted Girl",
        "Portuguese_Pompouslady": "Pompous lady",
        "Portuguese_Grinch": "Grinch",
        "Portuguese_Debator": "Debator",
        "Portuguese_SweetGirl": "Sweet Girl",
        "Portuguese_AttractiveGirl": "Attractive Girl",
        "Portuguese_ThoughtfulMan": "Thoughtful Man",
        "Portuguese_PlayfulGirl": "Playful Girl",
        "Portuguese_GorgeousLady": "Gorgeous Lady",
        "Portuguese_LovelyLady": "Lovely Lady",
        "Portuguese_SereneWoman": "Serene Woman",
        "Portuguese_SadTeen": "Sad Teen",
        "Portuguese_MaturePartner": "Mature Partner",
        "Portuguese_Comedian": "Comedian",
        "Portuguese_NaughtySchoolgirl": "Naughty Schoolgirl",
        "Portuguese_Narrator": "Narrator",
        "Portuguese_ToughBoss": "Tough Boss",
        "Portuguese_Fussyhostess": "Fussy hostess",
        "Portuguese_Dramatist": "Dramatist",
        "Portuguese_Steadymentor": "Steady Mentor",
        "Portuguese_Jovialman": "Jovial Man",
        "Portuguese_CharmingQueen": "Charming Queen",
        "Portuguese_SantaClaus": "Santa Claus",
        "Portuguese_Rudolph": "Rudolph",
        "Portuguese_Arnold": "Arnold",
        "Portuguese_CharmingSanta": "Charming Santa",
        "Portuguese_CharmingLady": "Charming Lady",
        "Portuguese_Ghost": "Ghost",
        "Portuguese_HumorousElder": "Humorous Elder",
        "Portuguese_CalmLeader": "Calm Leader",
        "Portuguese_GentleTeacher": "Gentle Teacher",
        "Portuguese_EnergeticBoy": "Energetic Boy",
        "Portuguese_ReliableMan": "Reliable Man",
        "Portuguese_SereneElder": "Serene Elder",
        "Portuguese_GrimReaper": "Grim Reaper",
        "Portuguese_AssertiveQueen": "Assertive Queen",
        "Portuguese_WhimsicalGirl": "Whimsical Girl",
        "Portuguese_StressedLady": "Stressed Lady",
        "Portuguese_FriendlyNeighbor": "Friendly Neighbor",
        "Portuguese_CaringGirlfriend": "Caring Girlfriend",
        "Portuguese_PowerfulSoldier": "Powerful Soldier",
        "Portuguese_FascinatingBoy": "Fascinating Boy",
        "Portuguese_RomanticHusband": "Romantic Husband",
        "Portuguese_StrictBoss": "Strict Boss",
        "Portuguese_InspiringLady": "Inspiring Lady",
        "Portuguese_PlayfulSpirit": "Playful Spirit",
        "Portuguese_ElegantGirl": "Elegant Girl",
        "Portuguese_CompellingGirl": "Compelling Girl",
        "Portuguese_PowerfulVeteran": "Powerful Veteran",
        "Portuguese_SensibleManager": "Sensible Manager",
        "Portuguese_ThoughtfulLady": "Thoughtful Lady",
        "Portuguese_TheatricalActor": "Theatrical Actor",
        "Portuguese_FragileBoy": "Fragile Boy",
        "Portuguese_ChattyGirl": "Chatty Girl",
        "Portuguese_Conscientiousinstructor": "Conscientious Instructor",
        "Portuguese_RationalMan": "Rational Man",
        "Portuguese_WiseScholar": "Wise Scholar",
        "Portuguese_FrankLady": "Frank Lady",
        "Portuguese_DeterminedManager": "Determined Manager",
    },
    "ru-RU": {
        "Russian_HandsomeChildhoodFriend": "Handsome Childhood Friend",
        "Russian_BrightHeroine": "Bright Queen",
        "Russian_AmbitiousWoman": "Ambitious Woman",
        "Russian_ReliableMan": "Reliable Man",
        "Russian_CrazyQueen": "Crazy Girl",
        "Russian_PessimisticGirl": "Pessimistic Girl",
        "Russian_AttractiveGuy": "Attractive Guy",
        "Russian_Bad-temperedBoy": "Bad-tempered Boy",
    },
    "tr-TR": {
        "Turkish_CalmWoman": "Calm Woman",
        "Turkish_Trustworthyman": "Trustworthy man",
    },
    "uk-UA": {
        "Ukrainian_CalmWoman": "Calm Woman",
        "Ukrainian_WiseScholar": "Wise Scholar",
    },
    "vi-VN": {
        "Vietnamese_kindhearted_girl": "Kind-hearted girl",
    },
    "th-TH": {
        "Thai_male_1_sample8": "Serene Man",
        "Thai_male_2_sample2": "Friendly Man",
        "Thai_female_1_sample1": "Confident Woman",
        "Thai_female_2_sample2": "Energetic Woman",
    },
    "pl-PL": {
        "Polish_male_1_sample4": "Male Narrator",
        "Polish_male_2_sample3": "Male Anchor",
        "Polish_female_1_sample1": "Calm Woman",
        "Polish_female_2_sample3": "Casual Woman",
    },
    "ro-RO": {
        "Romanian_male_1_sample2": "Reliable Man",
        "Romanian_male_2_sample1": "Energetic Youth",
        "Romanian_female_1_sample4": "Optimistic Youth",
        "Romanian_female_2_sample1": "Gentle Woman",
    },
    "el-GR": {
        "greek_male_1a_v1": "Thoughtful Mentor",
        "Greek_female_1_sample1": "Gentle Lady",
        "Greek_female_2_sample3": "Girl Next Door",
    },
    "cs-CZ": {
        "czech_male_1_v1": "Assured Presenter",
        "czech_female_5_v7": "Steadfast Narrator",
        "czech_female_2_v2": "Elegant Lady",
    },
    "fi-FI": {
        "finnish_male_3_v1": "Upbeat Man",
        "finnish_male_1_v2": "Friendly Boy",
        "finnish_female_4_v1": "Assetive Woman",
    },
    "hi-IN": {
        "hindi_male_1_v2": "Trustworthy Advisor",
        "hindi_female_2_v1": "Tranquil Woman",
        "hindi_female_1_v2": "News Anchor",
    },
    "zh-CN": {
        "Chinese (Mandarin)_Reliable_Executive": "Reliable Executive",
        "Chinese (Mandarin)_News_Anchor": "News Anchor",
        "Chinese (Mandarin)_Unrestrained_Young_Man": "Unrestrained Young Man",
        "Chinese (Mandarin)_Mature_Woman": "Mature Woman",
        "Arrogant_Miss": "Arrogant Miss",
        "Robot_Armor": "Robot Armor",
        "Chinese (Mandarin)_Kind-hearted_Antie": "Kind-hearted Antie",
        "Chinese (Mandarin)_HK_Flight_Attendant": "HK Flight Attendant",
        "Chinese (Mandarin)_Humorous_Elder": "Humorous Elder",
        "Chinese (Mandarin)_Gentleman": "Gentleman",
        "Chinese (Mandarin)_Warm_Bestie": "Warm Bestie",
        "Chinese (Mandarin)_Stubborn_Friend": "Stubborn Friend",
        "Chinese (Mandarin)_Sweet_Lady": "Sweet Lady",
        "Chinese (Mandarin)_Southern_Young_Man": "Southern Young Man",
        "Chinese (Mandarin)_Wise_Women": "Wise Women",
        "Chinese (Mandarin)_Gentle_Youth": "Gentle Youth",
        "Chinese (Mandarin)_Warm_Girl": "Warm Girl",
        "Chinese (Mandarin)_Male_Announcer": "Male Announcer",
        "Chinese (Mandarin)_Kind-hearted_Elder": "Kind-hearted Elder",
        "Chinese (Mandarin)_Cute_Spirit": "Cute Spirit",
        "Chinese (Mandarin)_Radio_Host": "Radio Host",
        "Chinese (Mandarin)_Lyrical_Voice": "Lyrical Voice",
        "Chinese (Mandarin)_Straightforward_Boy": "Straightforward Boy",
        "Chinese (Mandarin)_Sincere_Adult": "Sincere Adult",
        "Chinese (Mandarin)_Gentle_Senior": "Gentle Senior",
        "Chinese (Mandarin)_Crisp_Girl": "Crisp Girl",
        "Chinese (Mandarin)_Pure-hearted_Boy": "Pure-hearted Boy",
        "Chinese (Mandarin)_Soft_Girl": "Soft Girl",
        "Chinese (Mandarin)_IntellectualGirl": "Intellectual Girl",
        "Chinese (Mandarin)_Warm_HeartedGirl": "Warm-hearted Girl",
        "Chinese (Mandarin)_Laid_BackGirl": "Laid-back Girl",
        "Chinese (Mandarin)_ExplorativeGirl": "Explorative Girl",
        "Chinese (Mandarin)_Warm-HeartedAunt": "Warm-hearted Aunt",
        "Chinese (Mandarin)_BashfulGirl": "Bashful Girl",
    },
    "zh-HK": {
        "Cantonese_ProfessionalHost (F)": "Professional Female Host",
        "Cantonese_GentleLady": "Gentle Lady",
        "Cantonese_ProfessionalHost (M)": "Professional Male Host",
        "Cantonese_PlayfulMan": "Playful Man",
        "Cantonese_CuteGirl": "Cute Girl",
        "Cantonese_KindWoman": "Kind Woman",
    },
}